### ISSUE TITLE
Issue installing on Ubuntu 20.04.1 LTS using python 3.7.3

### ISSUE THREAD

**Issue by thoreauA** [stefanseefeld/faber#26]
Hi there!
I need faber in order to build the library Boost.Python .
When running "faber" in my terminal this is the output:
`Traceback (most recent call last):
 File "/home/user/anaconda3/bin/faber", line 33, in <module>
   sys.exit(load_entry_point('faber==0.4.2', 'console_scripts', 'faber')())
  File "/home/user/anaconda3/bin/faber", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/user/anaconda3/lib/python3.7/site-packages/importlib_metadata/api.py", line 310, in distribution
    return Distribution.from_name(package)
  File "/home/user/anaconda3/lib/python3.7/site-packages/importlib_metadata/api.py", line 158, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.api.PackageNotFoundError: faber`

Could you help me to figure out the problem? Thank you in advance!

**Comment by thoreauA** [comment]
Solved by updating all packages in anaconda prompt by: 
`conda update -n root conda`   latest conda version installed
 `conda update --all`  update all packages in the current environment to the latest version
